# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SciAI',
                'doc_host': 'https://Positron00.github.io',
                'git_url': 'https://github.com/Positron00/SciAI',
                'lib_path': 'SciAI'},
  'syms': {'SciAI.core': {'SciAI.core.foo': ('core.html#foo', 'SciAI/core.py')}}}
