"""This is where users start to interact with the underlying LLM and agents."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['REPLICATE_API_TOKEN', 'taskRouter']

# %% ../nbs/00_core.ipynb 3
# install dependencies
# %pip install replicate
# %pip install gradio
# %pip install langchain

# %% ../nbs/00_core.ipynb 4
# import replicate
# import gradio
# import langchain

import os
from getpass import getpass

REPLICATE_API_TOKEN = getpass()
os.environ["REPLICATE_API_TOKEN"] = REPLICATE_API_TOKEN

# %% ../nbs/00_core.ipynb 6
# A chatbot that allows users to interact with an LLM
import gradio as gr

def taskRouter(message, history):
    if message.endswith("?"):
        return "Good question!"
    elif "Hello" in message:
        return "Hello! How can I help?"
    else:
        return "Let me work on that...."

gr.ChatInterface(
    taskRouter,
    chatbot=gr.Chatbot(height=300,placeholder="<strong>Your Personal Science AI Assistant</strong><br>Ask Me Anything"),
    textbox=gr.Textbox(placeholder="How can I help?", container=False, scale=7),
    title="SciAI Assistant",
    description="Ask me any question or carry out a task",
    theme="soft",
    examples=["Hello", "What's new last week in neuroscience?", "I need help analyze some data"],
    cache_examples=True,
    retry_btn=None,
    undo_btn="Delete Previous",
    clear_btn="Clear",
).launch(share=True)
